// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATGCEy9ijSPgd603v1nZCRrgWfPCZjgi4',
    appId: '1:270133261516:web:f1295fb03c267e1776be69',
    messagingSenderId: '270133261516',
    projectId: 'ppbcs1',
    authDomain: 'ppbcs1.firebaseapp.com',
    storageBucket: 'ppbcs1.firebasestorage.app',
    measurementId: 'G-N0TVE9K7KM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC58hx0BaElyj8UhkYpK8IXGxNWK48JiZ4',
    appId: '1:270133261516:android:31c45b92667df9da76be69',
    messagingSenderId: '270133261516',
    projectId: 'ppbcs1',
    storageBucket: 'ppbcs1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATGCEy9ijSPgd603v1nZCRrgWfPCZjgi4',
    appId: '1:270133261516:web:e76c046377f3d20676be69',
    messagingSenderId: '270133261516',
    projectId: 'ppbcs1',
    authDomain: 'ppbcs1.firebaseapp.com',
    storageBucket: 'ppbcs1.firebasestorage.app',
    measurementId: 'G-6EJT4NLY3V',
  );
}